CREATE TABLE `roles` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`LIBELLE` VARCHAR(50) NOT NULL,
	`CODE` VARCHAR(10) NOT NULL,
	`ACTIF` TINYINT(1) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `ID_UNIQUE` (`ID`),
	UNIQUE INDEX `LIBELLE` (`LIBELLE`),
	UNIQUE INDEX `unique_code` (`CODE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=18
;

CREATE TABLE `utilisateurs` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`NOM` VARCHAR(100) NULL DEFAULT NULL,
	`PASSWORD` VARCHAR(100) NOT NULL,
	`CODE` VARCHAR(10) NULL DEFAULT NULL,
	`EMAIL` VARCHAR(100) NULL DEFAULT NULL,
	`ACTIF` TINYINT(1) NOT NULL,
	`PRENOM` VARCHAR(100) NULL DEFAULT NULL,
	`LOGIN` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `LOGIN_UNIQUE` (`LOGIN`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1024
;

CREATE TABLE `utilisateurs_roles` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`ID_UTILISATEUR` INT(11) NOT NULL,
	`ID_ROLE` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `ID_UNIQUE` (`ID`),
	UNIQUE INDEX `unique_utilisateur_role` (`ID_UTILISATEUR`, `ID_ROLE`),
	INDEX `fk_UTILISATEURS_ROLES_UTILISATEURS1_idx` (`ID_UTILISATEUR`),
	INDEX `fk_UTILISATEURS_ROLES_ROLES1_idx` (`ID_ROLE`),
	CONSTRAINT `fk_UTILISATEURS_ROLES_ROLES1` FOREIGN KEY (`ID_ROLE`) REFERENCES `roles` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT `fk_UTILISATEURS_ROLES_UTILISATEURS1` FOREIGN KEY (`ID_UTILISATEUR`) REFERENCES `utilisateurs` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=42
;
