CREATE TABLE `communes` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`NOM` VARCHAR(100) NOT NULL,
	`CODE_DEPARTEMENT` VARCHAR(10) NOT NULL,
	`CODE_POSTAL` VARCHAR(10) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `ID_UNIQUE` (`ID`),
	UNIQUE INDEX `unique_nom` (`NOM`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=18
;


INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34001', 'ABEILHAN', '34', '34290');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34002', 'ADISSAN', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34003', 'AGDE', '34', '34300');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34004', 'AGEL', '34', '34210');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34005', 'AGONES', '34', '34190');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34006', 'AIGNE', '34', '34210');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34007', 'AIGUES VIVES', '34', '34210');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34009', 'ALIGNAN DU VENT', '34', '34290');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34010', 'ANIANE', '34', '34150');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34011', 'ARBORAS', '34', '34150');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34012', 'ARGELLIERS', '34', '34380');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34013', 'ASPIRAN', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34014', 'ASSAS', '34', '34820');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34015', 'ASSIGNAN', '34', '34360');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34016', 'AUMELAS', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34017', 'AUMES', '34', '34530');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34018', 'AUTIGNAC', '34', '34480');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34019', 'AVENE', '34', '34260');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34020', 'AZILLANET', '34', '34210');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34021', 'BABEAU BOULDOUX', '34', '34360');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34022', 'BAILLARGUES', '34', '34670');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34024', 'BALARUC LE VIEUX', '34', '34540');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34023', 'BALARUC LES BAINS', '34', '34540');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34025', 'BASSAN', '34', '34290');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34026', 'BEAUFORT', '34', '34210');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34027', 'BEAULIEU', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34028', 'BEDARIEUX', '34', '34600');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34029', 'BELARGA', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34030', 'BERLOU', '34', '34360');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34031', 'BESSAN', '34', '34550');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34032', 'BEZIERS', '34', '34500');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34033', 'BOISSERON', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34034', 'BOISSET', '34', '34220');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34037', 'BOUJAN SUR LIBRON', '34', '34760');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34039', 'BOUZIGUES', '34', '34140');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34040', 'BRENAS', '34', '34650');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34041', 'BRIGNAC', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34042', 'BRISSAC', '34', '34190');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34043', 'BUZIGNARGUES', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34044', 'CABREROLLES', '34', '34480');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34045', 'CABRIERES', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34046', 'CAMBON ET SALVERGUES', '34', '34330');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34047', 'CAMPAGNAN', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34048', 'CAMPAGNE', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34049', 'CAMPLONG', '34', '34260');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34050', 'CANDILLARGUES', '34', '34130');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34051', 'CANET', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34052', 'CAPESTANG', '34', '34310');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34053', 'CARLENCAS ET LEVAS', '34', '34600');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34926', 'CARNON PLAGE', '34', '34280');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34054', 'CASSAGNOLES', '34', '34210');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34055', 'CASTANET LE HAUT', '34', '34610');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34056', 'CASTELNAU DE GUERS', '34', '34120');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34057', 'CASTELNAU LE LEZ', '34', '34170');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34058', 'CASTRIES', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34060', 'CAUSSE DE LA SELLE', '34', '34380');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34061', 'CAUSSES ET VEYRAN', '34', '34490');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34062', 'CAUSSINIOJOULS', '34', '34600');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34063', 'CAUX', '34', '34720');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34065', 'CAZEDARNES', '34', '34460');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34066', 'CAZEVIEILLE', '34', '34270');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34067', 'CAZILHAC', '34', '34190');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34068', 'CAZOULS D''HERAULT', '34', '34120');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34069', 'CAZOULS LES BEZIERS', '34', '34370');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34070', 'CEBAZAN', '34', '34360');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34071', 'CEILHES ET ROCOZELS', '34', '34260');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34072', 'CELLES', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34073', 'CERS', '34', '34420');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34074', 'CESSENON SUR ORB', '34', '34460');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34075', 'CESSERAS', '34', '34210');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34076', 'CEYRAS', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34077', 'CLAPIERS', '34', '34830');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34078', 'CLARET', '34', '34270');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34079', 'CLERMONT L''HERAULT', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34080', 'COLOMBIERES SUR ORB', '34', '34390');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34081', 'COLOMBIERS', '34', '34440');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34082', 'COMBAILLAUX', '34', '34980');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34083', 'COMBES', '34', '34240');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34084', 'CORNEILHAN', '34', '34490');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34085', 'COULOBRES', '34', '34290');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34086', 'COURNIOU', '34', '34220');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34087', 'COURNONSEC', '34', '34660');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34088', 'COURNONTERRAL', '34', '34660');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34089', 'CREISSAN', '34', '34370');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34092', 'CRUZY', '34', '34310');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34093', 'DIO ET VALQUIERES', '34', '34650');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34094', 'ESPONDEILHAN', '34', '34290');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34095', 'FABREGUES', '34', '34690');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34096', 'FAUGERES', '34', '34600');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34097', 'FELINES MINERVOIS', '34', '34210');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34098', 'FERRALS LES MONTAGNES', '34', '34210');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34099', 'FERRIERES LES VERRERIES', '34', '34190');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34100', 'FERRIERES POUSSAROU', '34', '34360');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34101', 'FLORENSAC', '34', '34510');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34102', 'FONTANES', '34', '34270');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34103', 'FONTES', '34', '34320');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34104', 'FOS', '34', '34320');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34105', 'FOUZILHON', '34', '34480');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34106', 'FOZIERES', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34107', 'FRAISSE SUR AGOUT', '34', '34330');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34108', 'FRONTIGNAN', '34', '34110');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34109', 'GABIAN', '34', '34320');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34110', 'GALARGUES', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34111', 'GANGES', '34', '34190');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34112', 'GARRIGUES', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34113', 'GIGEAN', '34', '34770');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34114', 'GIGNAC', '34', '34150');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34115', 'GORNIES', '34', '34190');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34116', 'GRABELS', '34', '34790');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34117', 'GRAISSESSAC', '34', '34260');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34118', 'GUZARGUES', '34', '34820');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34119', 'HEREPIAN', '34', '34600');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34120', 'JACOU', '34', '34830');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34121', 'JONCELS', '34', '34650');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34122', 'JONQUIERES', '34', '34725');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34123', 'JUVIGNAC', '34', '34990');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34035', 'LA BOISSIERE', '34', '34150');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34059', 'LA CAUNETTE', '34', '34210');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34344', 'LA GRANDE MOTTE', '34', '34280');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34141', 'LA LIVINIERE', '34', '34210');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34923', 'LA PEYRADE', '34', '34110');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34293', 'LA SALVETAT SUR AGOUT', '34', '34330');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34312', 'LA TOUR SUR ORB', '34', '34260');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34317', 'LA VACQUERIE ET SAINT MARTIN DE CASTRIES', '34', '34520');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34124', 'LACOSTE', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34125', 'LAGAMAS', '34', '34150');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34126', 'LAMALOU LES BAINS', '34', '34240');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34127', 'LANSARGUES', '34', '34130');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34128', 'LAROQUE', '34', '34190');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34129', 'LATTES', '34', '34970');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34130', 'LAURENS', '34', '34480');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34131', 'LAURET', '34', '34270');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34132', 'LAUROUX', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34133', 'LAVALETTE', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34134', 'LAVERUNE', '34', '34880');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34036', 'LE BOSC', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34038', 'LE BOUSQUET D''ORB', '34', '34260');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34902', 'LE CAP D''AGDE', '34', '34300');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34064', 'LE CAYLAR', '34', '34520');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34090', 'LE CRES', '34', '34920');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34091', 'LE CROS', '34', '34520');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34210', 'LE POUGET', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34211', 'LE POUJOL SUR ORB', '34', '34600');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34216', 'LE PRADAL', '34', '34600');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34220', 'LE PUECH', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34305', 'LE SOULIE', '34', '34330');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34314', 'LE TRIADOU', '34', '34270');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34008', 'LES AIRES', '34', '34600');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34153', 'LES MATELLES', '34', '34270');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34205', 'LES PLANS', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34230', 'LES RIVES', '34', '34520');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34135', 'LESPIGNAN', '34', '34710');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34136', 'LEZIGNAN LA CEBE', '34', '34120');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34137', 'LIAUSSON', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34138', 'LIEURAN CABRIERES', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34139', 'LIEURAN LES BEZIERS', '34', '34290');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34140', 'LIGNAN SUR ORB', '34', '34490');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34142', 'LODEVE', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34143', 'LOUPIAN', '34', '34140');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34144', 'LUNAS', '34', '34650');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34145', 'LUNEL', '34', '34400');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34146', 'LUNEL VIEL', '34', '34400');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34147', 'MAGALAS', '34', '34480');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34148', 'MARAUSSAN', '34', '34370');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34149', 'MARGON', '34', '34320');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34150', 'MARSEILLAN', '34', '34340');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34901', 'MARSEILLAN PLAGE', '34', '34340');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34151', 'MARSILLARGUES', '34', '34590');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34152', 'MAS DE LONDRES', '34', '34380');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34154', 'MAUGUIO', '34', '34130');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34155', 'MAUREILHAN', '34', '34370');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34156', 'MERIFONS', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34157', 'MEZE', '34', '34140');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34158', 'MINERVE', '34', '34210');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34159', 'MIREVAL', '34', '34110');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34160', 'MONS', '34', '34390');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34161', 'MONTADY', '34', '34310');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34162', 'MONTAGNAC', '34', '34530');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34163', 'MONTARNAUD', '34', '34570');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34164', 'MONTAUD', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34165', 'MONTBAZIN', '34', '34560');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34166', 'MONTBLANC', '34', '34290');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34167', 'MONTELS', '34', '34310');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34168', 'MONTESQUIEU', '34', '34320');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34169', 'MONTFERRIER SUR LEZ', '34', '34980');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34170', 'MONTOULIERS', '34', '34310');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34171', 'MONTOULIEU', '34', '34190');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34172', 'MONTPELLIER', '34', '34000');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34173', 'MONTPEYROUX', '34', '34150');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34174', 'MOULES ET BAUCELS', '34', '34190');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34175', 'MOUREZE', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34176', 'MUDAISON', '34', '34130');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34177', 'MURLES', '34', '34980');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34178', 'MURVIEL LES BEZIERS', '34', '34490');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34179', 'MURVIEL LES MONTPELLIER', '34', '34570');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34180', 'NEBIAN', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34181', 'NEFFIES', '34', '34320');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34182', 'NEZIGNAN L''EVEQUE', '34', '34120');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34183', 'NISSAN LEZ ENSERUNE', '34', '34440');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34184', 'NIZAS', '34', '34320');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34185', 'NOTRE DAME DE LONDRES', '34', '34380');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34186', 'OCTON', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34187', 'OLARGUES', '34', '34390');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34188', 'OLMET ET VILLECUN', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34189', 'OLONZAC', '34', '34210');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34190', 'OUPIA', '34', '34210');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34191', 'PAILHES', '34', '34490');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34192', 'PALAVAS LES FLOTS', '34', '34250');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34193', 'PARDAILHAN', '34', '34360');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34194', 'PAULHAN', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34195', 'PEGAIROLLES DE BUEGES', '34', '34380');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34196', 'PEGAIROLLES DE L''ESCALETTE', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34197', 'PERET', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34198', 'PEROLS', '34', '34470');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34199', 'PEZENAS', '34', '34120');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34200', 'PEZENES LES MINES', '34', '34600');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34201', 'PIERRERUE', '34', '34360');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34202', 'PIGNAN', '34', '34570');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34203', 'PINET', '34', '34850');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34927', 'PLAISANCE', '34', '34610');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34204', 'PLAISSAN', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34206', 'POILHES', '34', '34310');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34207', 'POMEROLS', '34', '34810');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34208', 'POPIAN', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34209', 'PORTIRAGNES', '34', '34420');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34212', 'POUJOLS', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34213', 'POUSSAN', '34', '34560');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34214', 'POUZOLLES', '34', '34480');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34215', 'POUZOLS', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34217', 'PRADES LE LEZ', '34', '34730');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34218', 'PRADES SUR VERNAZOBRE', '34', '34360');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34219', 'PREMIAN', '34', '34390');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34221', 'PUECHABON', '34', '34150');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34222', 'PUILACHER', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34223', 'PUIMISSON', '34', '34480');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34224', 'PUISSALICON', '34', '34480');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34225', 'PUISSERGUIER', '34', '34620');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34226', 'QUARANTE', '34', '34310');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34227', 'RESTINCLIERES', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34228', 'RIEUSSEC', '34', '34220');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34229', 'RIOLS', '34', '34220');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34231', 'ROMIGUIERES', '34', '34650');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34232', 'ROQUEBRUN', '34', '34460');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34233', 'ROQUEREDONDE', '34', '34650');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34234', 'ROQUESSELS', '34', '34320');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34235', 'ROSIS', '34', '34610');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34236', 'ROUET', '34', '34380');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34237', 'ROUJAN', '34', '34320');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34238', 'SAINT ANDRE DE BUEGES', '34', '34190');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34239', 'SAINT ANDRE DE SANGONIS', '34', '34725');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34240', 'SAINT AUNES', '34', '34130');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34241', 'SAINT BAUZILLE DE LA SYLVE', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34242', 'SAINT BAUZILLE DE MONTMEL', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34243', 'SAINT BAUZILLE DE PUTOIS', '34', '34190');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34244', 'SAINT BRES', '34', '34670');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34245', 'SAINT CHINIAN', '34', '34360');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34246', 'SAINT CHRISTOL', '34', '34400');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34247', 'SAINT CLEMENT DE RIVIERE', '34', '34980');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34249', 'SAINT DREZERY', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34250', 'SAINT ETIENNE D''ALBAGNAN', '34', '34390');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34251', 'SAINT ETIENNE DE GOURGAS', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34252', 'SAINT ETIENNE ESTRECHOUX', '34', '34260');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34253', 'SAINT FELIX DE L''HERAS', '34', '34520');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34254', 'SAINT FELIX DE LODEZ', '34', '34725');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34255', 'SAINT GELY DU FESC', '34', '34980');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34258', 'SAINT GENIES DE FONTEDIT', '34', '34480');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34257', 'SAINT GENIES DE VARENSAL', '34', '34610');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34256', 'SAINT GENIES DES MOURGUES', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34259', 'SAINT GEORGES D''ORQUES', '34', '34680');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34260', 'SAINT GERVAIS SUR MARE', '34', '34610');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34261', 'SAINT GUILHEM LE DESERT', '34', '34150');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34262', 'SAINT GUIRAUD', '34', '34725');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34263', 'SAINT HILAIRE DE BEAUVOIR', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34264', 'SAINT JEAN DE BUEGES', '34', '34380');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34265', 'SAINT JEAN DE CORNIES', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34266', 'SAINT JEAN DE CUCULLES', '34', '34270');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34267', 'SAINT JEAN DE FOS', '34', '34150');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34268', 'SAINT JEAN DE LA BLAQUIERE', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34269', 'SAINT JEAN DE MINERVOIS', '34', '34360');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34270', 'SAINT JEAN DE VEDAS', '34', '34430');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34271', 'SAINT JULIEN', '34', '34390');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34272', 'SAINT JUST', '34', '34400');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34273', 'SAINT MARTIN DE L''ARCON', '34', '34390');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34274', 'SAINT MARTIN DE LONDRES', '34', '34380');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34276', 'SAINT MATHIEU DE TREVIERS', '34', '34270');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34277', 'SAINT MAURICE NAVACELLES', '34', '34520');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34278', 'SAINT MICHEL', '34', '34520');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34279', 'SAINT NAZAIRE DE LADAREZ', '34', '34490');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34280', 'SAINT NAZAIRE DE PEZAN', '34', '34400');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34281', 'SAINT PARGOIRE', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34282', 'SAINT PAUL ET VALMALLE', '34', '34570');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34283', 'SAINT PIERRE DE LA FAGE', '34', '34520');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34285', 'SAINT PONS DE MAUCHIENS', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34284', 'SAINT PONS DE THOMIERES', '34', '34220');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34286', 'SAINT PRIVAT', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34287', 'SAINT SATURNIN DE LUCIAN', '34', '34725');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34288', 'SAINT SERIES', '34', '34400');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34289', 'SAINT THIBERY', '34', '34630');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34291', 'SAINT VINCENT D''OLARGUES', '34', '34390');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34290', 'SAINT VINCENT DE BARBEYRARGUES', '34', '34730');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34248', 'SAINTE CROIX DE QUINTILLARGUES', '34', '34270');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34292', 'SALASC', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34294', 'SATURARGUES', '34', '34400');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34295', 'SAUSSAN', '34', '34570');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34296', 'SAUSSINES', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34297', 'SAUTEYRARGUES', '34', '34270');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34298', 'SAUVIAN', '34', '34410');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34299', 'SERIGNAN', '34', '34410');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34300', 'SERVIAN', '34', '34290');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34301', 'SETE', '34', '34200');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34302', 'SIRAN', '34', '34210');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34303', 'SORBS', '34', '34520');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34304', 'SOUBES', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34306', 'SOUMONT', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34307', 'SUSSARGUES', '34', '34160');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34308', 'TAUSSAC LA BILLIERE', '34', '34600');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34309', 'TEYRAN', '34', '34820');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34310', 'THEZAN LES BEZIERS', '34', '34490');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34311', 'TOURBES', '34', '34120');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34313', 'TRESSAN', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34315', 'USCLAS D''HERAULT', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34316', 'USCLAS DU BOSC', '34', '34700');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34318', 'VACQUIERES', '34', '34270');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34319', 'VAILHAN', '34', '34320');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34320', 'VAILHAUQUES', '34', '34570');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34321', 'VALERGUES', '34', '34130');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34322', 'VALFLAUNES', '34', '34270');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34323', 'VALMASCLE', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34324', 'VALRAS PLAGE', '34', '34350');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34325', 'VALROS', '34', '34290');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34326', 'VELIEUX', '34', '34220');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34327', 'VENDARGUES', '34', '34740');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34328', 'VENDEMIAN', '34', '34230');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34329', 'VENDRES', '34', '34350');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34330', 'VERARGUES', '34', '34400');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34331', 'VERRERIES DE MOUSSANS', '34', '34220');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34332', 'VIAS', '34', '34450');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34333', 'VIC LA GARDIOLE', '34', '34110');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34334', 'VIEUSSAN', '34', '34390');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34335', 'VILLEMAGNE L''ARGENTIERE', '34', '34600');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34336', 'VILLENEUVE LES BEZIERS', '34', '34420');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34337', 'VILLENEUVE LES MAGUELONE', '34', '34750');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34338', 'VILLENEUVETTE', '34', '34800');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34339', 'VILLESPASSANS', '34', '34360');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34340', 'VILLETELLE', '34', '34400');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34341', 'VILLEVEYRAC', '34', '34560');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34342', 'VIOLS EN LAVAL', '34', '34380');
INSERT INTO `communes` (`id`, `nom`, `code_departement`, `code_postal`) VALUES ('34343', 'VIOLS LE FORT', '34', '34380');
