/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-yoni:Repo.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/my-pack
 */
package com.hh.ged.repositories;

import com.hh.ged.entities.Commune;
import com.hh.ged.entities.Role;
import org.springframework.data.repository.CrudRepository;

/**
 * {@link CrudRepository} for {@link Commune}
 * Created by rvl with celerio engine
 */
public interface CommuneRepo extends CrudRepository<Commune, Integer> {


}
