/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-yoni:Repo.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/my-pack
 */
package com.hh.ged.repositories;


import com.hh.ged.entities.Utilisateur;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;

import java.util.List;

/**
 * {@link CrudRepository} for {@link Utilisateur}
 * Created by rvl with celerio engine
 */
public interface UtilisateurRepo extends CrudRepository<Utilisateur, Integer> {

    /**
     * Rechercher un utilisateur par son login
     * Renvoie l'utilisateur et sa liste de role
     *
     * @param login
     * @throws Exception
     */
    @Query(" SELECT distinct u from Utilisateur u " +
        " INNER JOIN FETCH u.utilisateurRoleList ur " +
        " INNER JOIN FETCH ur.role r " +
        " WHERE u.login=?1 " +
        " AND u.actif=1 " +
        " AND r.actif=1 ")
    Utilisateur findByLogin(String login);


        @Query(" SELECT distinct u from Utilisateur u " +
        " INNER JOIN FETCH u.utilisateurRoleList ur " +
        " INNER JOIN FETCH ur.role r " )
    List<Utilisateur> findAllRoles();


}
